### ISSUE TITLE
Can you port Source Engine maps to the Xbox 360? If so, how?

### ISSUE THREAD

**Issue by metalex10** [snake-biscuits/bsp_tool#79]
Convert maps of valve maps , little to big endiand, in other words pc to x360, example l4d2 maps PC to x360, 
Is there a function like .saveAs for example? or convertTo...

**Comment by snake-biscuits** [comment]
It might be, I would need a way to test map changes on console
Would also probably need to build maps to the x360 engine limits

**Comment by snake-biscuits** [comment]
idk how Vphysics differs between pc and console either, so ported maps might not have physics

**Comment by metalex10** [comment]
There may be a method where pc default and console default are compared, because I think it is only the conversion between their own engines between endians

**Comment by metalex10** [comment]
is endian wrapper and compress with lzma

**Comment by metalex10** [comment]
ok, so how convert this maps to x360?

**Comment by snake-biscuits** [comment]
> It might be, I would need a way to test map changes on console
> Would also probably need to build maps to the x360 engine limits

### Testing
Figured out a way to do testing, using Xenia
Turns out Xenia can launch the extracted `default.xex`, & other modded files
Using Xenia Canary since it patches the game a little

Requires changing the following settings in `xenia-canary.config.toml`:
```toml
# safety net
break_on_unimplemented_instructions = false
# console commands
# "-dvd" helps the game run
# "-game hl2 +map credits" sets the map to Half-Life 2's credits
cl = "-dvd -game hl2 +map credits"
# text rendering
d3d12_readback_memexport = true
d3d12_readback_resolve = true
```
Using `cl="-dvd -game hl2 +map credits"` loads directly into the end credits of Half-Life 2
Choosing maps by name makes things easier than I was expecting
Was dreading modding menus / replacing files to launch into maps
Also means testing is extra fast, I can make a shortcut to open `OrangeBox/default.xex` w/ Xenia

Team Fortress 2 can't run any maps, gives an in-game error saying: "Lost Connection to Game Server"
I don't know if that means the locally hosted server or some master server
May have to get my Xbox360 out and compare the unemulated game at some point

### Engine Limits
I've started making a spreadsheet of how close Xbox360 maps get to the engine limits on PC
Right now they look pretty reasonable, I may already have some under the Xbox360 limits
Comparing against the equivalent PC maps is probably a good idea though

The Xbox360 limits I saw might be for the Xbox version of HL2
Or the Xbox360 limits are dynamic in some way

### Related Issues
 * https://github.com/xenia-project/game-compatibility/issues/255

Also, more Xbox360 games I haven't checked support for:
https://github.com/xenia-project/game-compatibility/issues?q=is%3Aopen+label%3Atech-engine-source+sort%3Aupdated-desc
